/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d2e7197d-6a69-4beb-bf2c-dce41fc5e9d6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SBQCJpa4Y",
    "aws_user_pools_web_client_id": "7mqvtcqahqmdi9om7vj96c18ir",
    "oauth": {}
};


export default awsmobile;
